### ISSUE TITLE
Documentation request: examples and/or getting started?

### ISSUE THREAD

**Issue by diemonster** [pipelined/vst2#1]
I just happened upon this project while searching for Golang / VST SDK bindings. Looks promising!

Are you at a point where it makes sense to have other people try out this package? I'm a Go developer, although I haven't worked with the VST SDK yet and I'm not educated on the common patterns. As such, a passthrough audio example [like this for JACK](https://github.com/xthexder/go-jack/blob/master/example/passthrough.go) would be really helpful.

**Comment by dudk** [comment]
Thanks @diemonster. Documentation and examples are missing indeed. I will try to add an example package or appropriate quickstart example.

Regards the current state, it's definetely very raw at this point. Some structures - like speakerArrangement are just mocked up or hardcoded at this moment, but I'm planning to continue this project. I'm currently building an audio pipeline, where this package will be a part of core functionality.

As starting point you can look into [test code](https://github.com/dudk/vst2/blob/master/vst2_test.go). It can give you an idea how to use it, but

**Comment by smolagakuba** [comment]
Hey, the test code link doesn't work. Could you upload a new example of how to use this repo?

**Comment by dudk** [comment]
@smolagakuba you can now refer to [example](https://godoc.org/github.com/pipelined/vst2) in godoc
