### ISSUE TITLE
go imports/module, example and opcodes

### ISSUE THREAD

**Issue by RobinKamps** [pipelined/vst2#13]
Good Evening,
thanks for you effort to bring vst to golang!

Just tried to get the example up and running, but ran into some minor problems:

1.
```
var data = signal.Float64([][]float64{
//Cannot convert expression of type [][]float64 to type Float64 
```

2.
Please consider to rename all of your modules from pipelined.dev to github.com/pipelined/: 

```
go get: github.com/pipelined/vst2@v0.6.0: parsing go.mod:
        module declares its path as: pipelined.dev/vst2
                but was required as: github.com/pipelined/vst2
```

Iam new to vst programming, so a few questions arise.
It would be awesome if you can give me a hint to the right direction :

1. I need to set initial patches for some plugins - i guess that could be done via the callback and the opcodes?
2. How to get all possible opcodes and perhaps possible values for any plugin? (i guess there is a api, wich returns these, because a daw stores and restores patch values as well)

**Comment by dudk** [comment]
Hello Robin, thank you for giving it a try! Please find the explanations below.

1. Can you tell me which version of `pipelined.dev/signal` package are you using in that code snippet? `pipelined.dev/signal` has been significantly refactored some time ago. `vst2` uses v0.5.1 and the latest release is v0.7.2 where all signal types has changed and you would hit this error. Right now I'm busy with migrating all packages to the latest version of `pipelined.dev/signal`.

2. Thank you for pointing this out, the instructions in README.md are outdated. You need to use `pipelined.dev/vst2` import path as it's the vanilla one.

Now to your bonus points. 

1. What do you mean by patches here? Set up parameter values?

2. If you want to check if plugin supports certain opcode, you can use `EffCanDo` opcode and pass in the string to check the desired capability. I haven't provided a golang-friendly API to easily do that though :-/ 

Let me know if I can help you with anything else.

**Comment by RobinKamps** [comment]
Hi Sergei,
thank you for your fast reply.
I tried different versions for vst2 and also for signal with the supplied example.
You are correct: if i use signal v0.5.1 on windows, the float error does not occur.

Instead i get a few errors on Windows from pipelined.dev/vst2 - sorry i was not able to fix them properly and do a pull request.
Errors are: 
```
# pipelined.dev/vst2
pipelined.dev\vst2@v0.6.0\vst2_windows.go:33:22: undefined: paths
pipelined.dev\vst2@v0.6.0\vst2_windows.go:40:30: undefined: l
pipelined.dev\vst2@v0.6.0\vst2_windows.go:42:74: undefined: l
pipelined.dev\vst2@v0.6.0\vst2_windows.go:44:2: undefined: l
pipelined.dev\vst2@v0.6.0\vst2_windows.go:45:2: undefined: l
pipelined.dev\vst2@v0.6.0\vst2_windows.go:50:3: undefined: l
pipelined.dev\vst2@v0.6.0\vst2_windows.go:51:86: undefined: l
pipelined.dev\vst2@v0.6.0\vst2_windows.go:53:19: cannot convert m (type uintptr) to type effectMain
pipelined.dev\vst2@v0.6.0\vst2_windows.go:61:4: cannot use nil as type handle in assignment
```
I guess the windows implementation is based on a removed/refactored parameter l instead of just a path string like the darwin implementation is. 

To my bonus questions: 
1. yes i mean how to recall a patch or preset if a vst2 plugin is loaded by providing a config, e.g. param key - value array or similar thing.
2. I read the vst2 design spec by steinberg, but im not sure if i fully understand the meaning of "opcodes", for what i understand is, that a vst2 plugin can provide a param key - value array so that the host can use the specified parameters to automate or control the plugin via a simple gui or the vst plugin can implement its own gui. What i do not get yet, is how and where a preset can be stored, how a preset can be loaded from the host to the plugin and how to retrieve the metainformations, eg. pridev param key names and possible values (the spec mentions that values should be float from 0 - 1 as a convention for non audio data).

**Comment by dudk** [comment]
This is correct. I think that I kind of forgot about windows for some time. I created a separate issue to track it there: #14. I'll also review your #15. 

Opcodes are specific parameters that are passed to plugin/host in callback functions. They allow to determine:

* what should plugin/host do with this callback;
* what are additional parameters passed in through pointers.

Each plugin has different capabilities, for example some of them can process midi and some of them cannot. Opcode `EffCanDo` can be used to check for capabilities.

What you are asking is a question about parameters and programs(presets). There are multiple opcodes that can help you to achieve what you want:

* The Effect type contains both a number of parameters and a number of programs;
* EffGetParameterProperties;
* EffGetParamLabel;
* EffGetParamDisplay;
* EffGetParamName;
* EffGetParameterProperties;
* EffBeginSetProgram;
* EffEndSetProgram;
* EffSetProgram;
* EffGetProgram;
* EffSetProgramName;
* EffGetProgramName;

I tried to capture what these opcodes do in the documentation.

**Comment by RobinKamps** [comment]
Thank you very much - after a few tries i managed to switch programs.
But i had to hardcode the logic for dispatching the opcodes inside the vst2 processor.go `func (v VST) Load(c HostCallbackFunc) *Plugin {`.
Is there a way to dispatch opcodes from outside the vst2 lib e.g. if it is used within pipe?

```
p, err := pipe.New(
		&pipe.Line{
                        //some pump,
			Processors: pipe.Processors(
				&vst2.Processor{
					VST: vst,
                                        //add a array or callbacks to dispatch some opcodes after plugin is loaded, but before processed
				},
			),
			// some sink.
		},
	)
```

**Comment by RobinKamps** [comment]
i changed the vst2 lib a bit, so that custom dispatches could be made after vst2.Open and before adding the vst2.Processor to the processor pipe.

let me know if i should do a pr.

https://github.com/RobinKamps/vst2/compare/windows_fix...RobinKamps:dispatch

**Comment by RobinKamps** [comment]
Hi Sergei,

if a pipe contains a vst, there happens to be an offset when the audio starts at the sink (the sound does not start at a sinked asset at 0 but at around 16000-20000 (around 0.400 seconds).
i guess it has something to do with the buffer of the vst or the processing time in there.
i tried to use a formula e.g. 32*bufferSize to determine the offset, but could not figure out, if this is correct (if i sum up added track lengths it does 

Is there a way to determine the start offset, or a way to seek the first position, where the audio in the assets is not 0?

Thank you very much in advance!

**Comment by dudk** [comment]
Hello Robin! Glad to hear about your progress. Could you please provide more details on what exactly are you trying to do? The most important information is what pipe components do you use and which versions.

**Comment by RobinKamps** [comment]
Good evening Sergej,

issue is solved - thank you very much for this awesome golang project!

FYI: problem/question occurred due two this two reasons:

1. if you use a pipe with a sink to an asset, the resulting asset always has 256 samples filled with zeros added at the end (could be bufferSize depended - i used 512 buffersize). Overall this is no problem, but one some cases it has to be taken into account
2. tests with multiple vsts showed that some vsts result in a offset at the start and thus even longer assets. Unfortunatley those offsets are not just plain zero filled, but can have some "artifacts" showing up in a wave-editor. Further investigations of the wave outputs showed, that the particular vst just had the sampleRate as an start offset - in my case the resulting assets were 44356 longer than the input - so i just had to cut the first 44100 samples and the last 256 samples.

pipe v0.7.0
signal v0.5.1

**Comment by RobinKamps** [comment]
Hi Sergej,

could you please give me some advice, how to use vst2.Ptr in Dispatch ? 

1. how to "read" the pointer value into a casted go value
  ```	
	result := ""
	rp := &result
	ptr :=  vst2.Ptr(rp)
	r := plugin.Dispatch(vst2.EffGetProgramName, 0,0, ptr, 0.0)
	fmt.Printf("%v\n", ptr) //will output an address
	fmt.Printf("%v\n", &ptr) //will output an address (also if i try to further "unpack" the addresses, i always get this address)
	/
```

2. how to write with a vst2.Ptr correctly (e.g. it should resolve to const_cast<char *> on the c side / cpp type)
    - if i write something i get the error: `panic: runtime error: cgo argument has Go pointer to Go pointer`.

```
         //i know - should use ReadUint32BE like https://play.golang.org/p/O1vKDZroZ1	
        dat, err := ioutil.ReadFile(storagePath + "DDGateP20.fxp") 
	if err != nil {
		log.Fatal(err)
	}

	value := vst2.Value(len(dat))
	ptr := vst2.Ptr(unsafe.Pointer(&dat))

	plugin.Dispatch(vst2.EffSetChunk,0,value,ptr, 0.0)

```

i get the error: `panic: runtime error: cgo argument has Go pointer to Go pointer`.
This is due to the []byte is a go pointer i guess.
https://github.com/golang/go/issues/14210

**Comment by dudk** [comment]
Hello Robin,

Those are very good questions! There are multiple things to keep in mind for both of these cases.

-  Refer to the documentation of [opcodes](https://github.com/pipelined/vst2/blob/b6c85cf7c64d46913b7570674f42ea8df02669b0/opcode.go#L26), I tried to describe required params there.

-  I want to encapsulate direct dispatch calls wherever is possible, because it requires to use `unsafe` package which is not really good for library API.

Going back to your specific cases:

1. You should use a pointer to [maxProgNameLen]uint8 array as parameter instead of string. Because `uint8` is an alias of `byte` type, it can be converted to `string` using [casting](https://stackoverflow.com/questions/56641843/how-to-convert-uint8-array-to-string).
2. `This is due to the []byte is a go pointer i guess.` You are absolutely correct here. The situation is more complicated, because maximum size of data is not defined. This means we cannot really instantiate the array of fixed size and pass it. As a workaround I suggest to try use Data pointer from [reflect.SliceHeader](https://golang.org/pkg/reflect/#SliceHeader).

Please let me know about your progress!

**Comment by RobinKamps** [comment]
Good Morning Sergej,

thank you very much - with an array of uint8s the reading part does work fine.

i am still trying to set a chunk via EffSetChunk.
main problem is how to use a []byte slice as uintptr (or the whole refect.SliceHeader).

```
//chunk is a byte[]
vst2.Ptr(uintptr(unsafe.Pointer(&chunk))) //is still a go pointer - i guess because unsafe.Pointer is a go pointer?
```

could you provide an example how to pass a []byte slice or array (or pointer to array) as a vst2.Ptr?

**Comment by dudk** [comment]
Hello Robin, you are welcome!

I think that you can try to use the following code:

```go
s := make([]byte, 10)
h := (*reflect.SliceHeader)(unsafe.Pointer(&s))
ptr := vst2.Ptr(unsafe.Pointer(h.Data))
```

Let me know if it works.

**Comment by dudk** [comment]
Hello @RobinKamps! Any luck here?

**Comment by RobinKamps** [comment]
Good evening Sergej,

your example code for the usage of the reflect.SliceHeader is working great - no "pointer to go pointer" anymore.
Thank you very much!

However im struggling to read the file/bytes in `binary.BigEndian.Uint32`.
Unfortunatly this is the format of all vst2 banks and patches (.fxp) are stored.
Reading BE32 files is not provided by the standard lib of golang.
There are just a few hints, how to read some bytes in BE32 ( https://medium.com/learning-the-go-programming-language/encoding-data-with-the-go-binary-package-42c7c0eb3e73 ) - but still i have no solution for just the whole file.
Furthermore on the Opcode: vst2.EffSetChunk the length of the data / pointer must be specified by `value` i think.


```
        dat, err := ioutil.ReadFile(storagePath + "P20.fxp") //or open as ReadSeaker if it is easier to convert to binary.BigEndian.Uint32
	if err != nil {
		log.Fatal(err)
	}

        //conversion or direct reading to binary.BigEndian.Uint32 is missing...

        // do not know either: Opcode: vst2.EffSetChunk needs the length as a value?
	value := vst2.Value(len(dat))

	h := (*reflect.SliceHeader)(unsafe.Pointer(&dat))
	ptr := vst2.Ptr(unsafe.Pointer(h.Data))


//dispatching the following opcodes does not throw any error, but does not load the desired patch/fxp at all

                        {
				Opcode: vst2.EffBeginSetProgram,
				Index:  0,
				Value:  0,
				Ptr:    nil,
				Opt:    0.0,
			},
			{
				Opcode: vst2.EffSetChunk,
				Index:  1,
				Value:  value,
				Ptr:    ptr,
				Opt:    0.0,
			},
			{
				Opcode: vst2.EffEndSetProgram,
				Index:  0,
				Value:  0,
				Ptr:    nil,
				Opt:    0.0,
			},

```

Do you know how to read the file in BE32 mode?

Not that urgent additional question:
I´ve got some plugins, wich work on windows only.
It was a complete pain to get viert lame even to compile on windows with cgo (wich i needed for the vst).
Since windows server are pure pain, too: Do you have any advice or know how to run vsts and this library under ubuntu server with wine?
(i´ve read vst plugins for windows can be run in wine: ardour can be compiled to archieve this - but it was said in some forums, that this is very special and not provided by the community as it alters the whole build of ardour and is kind of hard to do)

By the way: i absolutely owe you a beer or two ;-) for your awesome support and your great libraries! 
Perhaps we can meet in utrecht, if i´m nearby sometime.

**Comment by dudk** [comment]
Hello Robin!

I'm very glad that my advices and libs are useful! It would be really great to catch up for some beers ! :)  

I think that the snippet you shared is the one I had in my head. How do you validate that it didn't work? Do you read the parameters values after? Also, could you please share the preset file you're using, please? If it's still the case, I can help you with `binary.BigEndian.Uint32` test.

Regards your other questions:

> It was a complete pain to get viert lame even to compile on windows with cgo

What do you mean exactly? I thought that you just need to provide linking to lame header file using `CFLAGS`, isn't that right?

> Do you have any advice or know how to run vsts and this library under ubuntu server with wine?

Not as of this moment to be honest. Currently this library doesn't support VSTs in linux - they are built as shared libraries (.so files) there. Do you have any particular examples of such plugins? It sounds like an interesting challenge :)
