### ISSUE TITLE
Building plugins

### ISSUE THREAD

**Issue by dudk** [pipelined/vst2#35]
In theory this package should allow people building VST2 plugins in go. This issue will track the progress in this effort.

Compilation and build:

- [x] Create package to enable export of plugin functions;
- [x] Build a shared-lib with c-shared build mode;

Build command (OS X):

- [ ] [Convert](https://stackoverflow.com/questions/25321911/convert-a-to-dylib-in-mac-osx) shared library to dylib;
- [ ] Generate [manifest](https://gist.github.com/dudk/df0cc1c2db70956672aa3a72e95716f5);
- [ ] Create bundle [folder structure](https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW33);

**Comment by dudk** [comment]
Managed to build plugin, but hitting [this problem](https://github.com/golang/go/issues/22192) with loading plugin built with c-shared in go VST host.

**Comment by dudk** [comment]
Current branch builds Mach DYLIB. OS X expects VST plugins to be Mach BUNDLE. Looking for a solution.

**Comment by emicklei** [comment]
Maybe this helps, https://docstore.mik.ua/orelly/unix3/mac/ch05_03.htm

**Comment by dudk** [comment]
@emicklei unfortunately I'm not that strong with C ecosystem. I tried running `clang -bundle` command with both `.a` and `.dylib` files as input, but it gives just an empty bundle in return. I think that in general it expects some C/C++ files referencing that library as input.

It seems like `CMake` [allows](https://stackoverflow.com/questions/26239288/cmake-create-osx-bundle-for-dylib) to build Mach-O bundle for provided `.dylib`, but I have no idea where to start as I never used cmake before.

**Comment by emicklei** [comment]
Same here, C ecosystem is scaring me. Maybe it is time for me to change that but is not just C, also Apple, cgo, cpp,....

In the meantime, I appreciate your effort.

**Comment by dudk** [comment]
Positive news @emicklei I tried another host (Renoise) and it opened plugin, rendered param value and didn't crash! It seems that Ableton has some check for Mach-O bundle. I'll make a separate task to fix that in the future. 

It seems that Rust VST2 plugins built in [this library](https://github.com/RustAudio/vst-rs) are also just plain dylibs.

Intermediate progress: it's possible to build vst2 effects in go now. There is still a lot of work to do:

* Dispatch API, so users won't have to deal with `unsafe` package;
* Better abstractions for double buffers;

**Comment by dudk** [comment]
I split efforts for supporting plugins into separate [issues](https://github.com/pipelined/vst2/labels/plugin). I also created v0.10.0 milestone to identify what's a must for first release. Closing this.
