### ISSUE TITLE
Demo plugin not running. Is it out of date?

### ISSUE THREAD

**Issue by kendfss** [pipelined/vst2#58]
Hello, I'm on `go version go1.16.2 windows/amd64` trying to run the demoplugin/demo.go file but keep getting the following error
```shell
# command-line-arguments
.\demo.go:14:2: undefined: vst2.PluginAllocator
.\demo.go:14:57: undefined: vst2.Dispatcher
.\demo.go:21:4: unknown field 'InputChannels' in struct literal of type vst2.Plugin
.\demo.go:22:4: unknown field 'OutputChannels' in struct literal of type vst2.Plugin
.\demo.go:23:4: unknown field 'Parameters' in struct literal of type vst2.Plugin
.\demo.go:26:4: unknown field 'ProcessDoubleFunc' in struct literal of type vst2.Plugin
.\demo.go:36:4: unknown field 'ProcessFloatFunc' in struct literal of type vst2.Plugin
.\demo.go:46:6: undefined: vst2.Dispatcher
```

**Comment by dudk** [comment]
Hello @kendfss! Seems like your build command is missing a '--plugin' build tag. Could you confirm?

**Comment by kendfss** [comment]
Yes it was, sorry, how should I be building, @dudk?

**Comment by dudk** [comment]
You can build it with `go build --buildmode c-shared --tags plugin`. Please refer to the post that describes in detail how to build it for windows: https://pipelined.dev/2021/04/vst2-go-plugins/

I've created #59 to fix this.

**Comment by kendfss** [comment]
Sorry for missing that, and thanks!
