### ISSUE TITLE
Linux AMD64 cannot use _Ctype_longlong(flags) (value of type _Ctype_longlong) as _Ctype_long value in variable declaration

### ISSUE THREAD

**Issue by MartiniMoe** [pipelined/vst2#67]
I can't build this on Linux AMD64 because of the following error:

```
../../../go/pkg/mod/pipelined.dev/audio/vst2@v0.10.1-0.20230718065422-be1242fca4ab/plugin.go:141:97: cannot use _Ctype_longlong(flags) (value of type _Ctype_longlong) as _Ctype_long value in variable declaration
```

Changing the given line to

```
return (*TimeInfo)(unsafe.Pointer(uintptr(C.callbackHost(h.callback, cp, C.int(HostGetTime), 0, C.long(flags), nil, 0))))
```

seems to fix the issue and it builds successfully.

**Comment by MartiniMoe** [comment]
Hey, we are thinking of writing a NixOS derivation for sointu (which depends on vst2), so I wanted to ask, if there might be a fix for this soon, or if we should plan to patch this in our package (which would be totally fine, no pressure!!) :3

**Comment by vsariola** [comment]
I think the proper fix is: change the type into C.int64_t. This works on Windows and hopefully on linux/amd64 too

**Comment by MartiniMoe** [comment]
It also works on Linux :tada:
